Korrektur Übungsblatt 11
========================

Aufgabe 11.1 (a)
----------------
3/3


Aufgabe 11.1 (b)
----------------
4/4


Aufgabe 11.1 (c)
----------------
+---- test.txt ---
| ============================= test session starts ==============================
| platform linux -- Python 3.6.8, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
| cachedir: .cache
| rootdir: /mnt/c/Informatik/programm1/Übungsblätter/info1/sheet11, inifile:
| collecting ... collected 4 items
| 
| words.py::test_next_word_1 PASSED                                        [ 25%]
| words.py::test_next_word_2 PASSED                                        [ 50%]
| words.py::test_next_word_3 PASSED                                        [ 75%]
| words.py::test_next_word_4 PASSED                                        [100%]
| 
| =========================== 4 passed in 0.02 seconds ===========================
+-----------------
1/1


Aufgabe 11.2
------------
4/4


Aufgabe 11.3
------------
* traceback.txt existiert nicht
0/2


Aufgabe 11.4 (a)
----------------
2/2


Aufgabe 11.4 (b)
----------------
* test_flatten_1 wurde nicht definiert
* test_flatten_2 wurde nicht definiert
* test_flatten_3 wurde nicht definiert
* test_flatten_4 wurde nicht definiert
0/2


Aufgabe 11.5
------------
+---- erfahrungen.txt ---
| Aufwand ca. 3-4h
| 
| Die Aufgaben sind von machbarer Größe.
+------------------------
2/2


Gesamtpunktzahl
---------------
16/20
